//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApp2.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Account
    {
        public int Accid { get; set; }

        [Required(ErrorMessage ="enter the name")]
        public string Accname { get; set; }

        [Required(ErrorMessage = "enter the Email")]
        [EmailAddress]
        public string Email { get; set; }

        [Required(ErrorMessage = "enter the phone")]
        [MinLength(10,ErrorMessage ="Mobile number should be 10 digits")]
        public string phone { get; set; }

        public Nullable<int> balance { get; set; }
    }
}
